# Generated by Django 5.2.1 on 2025-09-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='recursos_vistos',
            field=models.TextField(blank=True, default=''),
        ),
    ]
